#ifndef _GLOBAL_VARIABLE_H_
#define _GLOBAL_VARIABLE_H_

#define BOARD_CH32_EVB_LORA 0
#define BOARD_CH32_TOS_LORA 1

#define BOARD_MODEL BOARD_CH32_EVB_LORA

//#define BOARD_MODEL BOARD_CH32_TOS_LORA

#endif
